<b>Project Data Mahasiswa</b><br>
Sampel 1000 data mahasiswa, beragam memiliki 10 kolom<br>
<ol>
    <li>Usia         : 18 - 22</li>
    <li>Gender       : L/P</li>
    <li>Jurusan      : TI, TS, TE, TM</li>
    <li>Asal Sekolah : SMA, SMK, MA</li>
    <li>Semester     : 1, 2, 3, 4, 5, 6, 7, 8</li>
    <li>Kelas        : Reguler, Karyawan, Blended</li>
    <li>Mata Kuliah  : Matematika, Fisika, kimia</li>
    <li>Absen        : Hadir, Izin, Sakit, Alfa</li>
    <li>IPK          : 2, 3, 4</li>
    <li>Kategori     : Beasiswa, NonBeasiswa</li>
</ol>

In [107]:
import numpy as np
import pandas as pd

n_data = 1000

usia = np.random.randint(18,23,size=n_data)
gender = np.random.choice(['L','P'],size=n_data)
jurusan = np.random.choice(['TI','TS','TE','TM'],size=n_data)
asalSekolah = np.random.choice(['SMA','SMK','MA'],size=n_data)
semester = np.random.randint(1,9,size=n_data)
kelas = np.random.choice(['Reguler','Karyawan','Blended'],size=n_data)
matkul = np.random.choice(['MTK','Fisika','Kimia'],size=n_data)
absen = np.random.choice(['Hadir','Izin','Sakit','Alfa'],size=n_data)
ipk = np.random.randint(2,5,size=n_data)
kategori = np.random.choice(['Beasiswa','Non Beasiswa'],size=n_data)

df = pd.DataFrame({
    'Usia' : usia,
    'Gender' : gender,
    'Jurusan' : jurusan,
    'Asal Sekolah' : asalSekolah,
    'Semester' : semester,
    'Kelas' : kelas,
    'Mata Kuliah' : matkul,
    'Absen' : absen,
    'IPK' : ipk,
    'Kategori' : kategori
})

print(df.info)
print(f"Usia mahasiswa termuda: {df.Usia.min()}")
print(f"Usia mahasiswa tertua: {df.Usia.max()}")
jmlL = df[df['Gender']=='L']
jmlP = df[df['Gender']=='P']
print(f"Jumlah mahasiswa laki-laki: {jmlL.size/10}")
print(f"Jumlah mahasiswa perempuan: {jmlP.size/10}")
jmlTI = df[df['Jurusan']=='TI']
jmlTS = df[df['Jurusan']=='TS']
jmlTE = df[df['Jurusan']=='TE']
jmlTM = df[df['Jurusan']=='TM']
print(f"Jumlah mahasiswa jurusan Teknik Informatika: {jmlTI.size/10}")
print(f"Jumlah mahasiswa jurusan Teknik Sipil      : {jmlTS.size/10}")
print(f"Jumlah mahasiswa jurusan Teknik Elektro    : {jmlTE.size/10}")
print(f"Jumlah mahasiswa jurusan Teknik Mesin      : {jmlTM.size/10}")
jmlSMA = df[df['Asal Sekolah']=='SMA']
jmlSMK = df[df['Asal Sekolah']=='SMK']
jmlMA = df[df['Asal Sekolah']=='MA']
print(f"Jumlah asal sekolah SMA: {jmlSMA.size/10}")
print(f"Jumlah asal sekolah SMk: {jmlSMK.size/10}")
print(f"Jumlah asal sekolah MA : {jmlMA.size/10}")
smstrTua = df[df['Semester']>=7]
print(f"Jumlah mahasiswa semester tua: {smstrTua.size}")
reguler = df[df['Kelas']=='Reguler']
karyawan = df[df['Kelas']=='Karyawan']
blended = df[df['Kelas']=='Blended']
print(f"Jumlah mahasiswa kelas reguler: {reguler.size/10}")
print(f"Jumlah mahasiswa kelas karyawan: {karyawan.size/10}")
print(f"Jumlah mahasiswa kelas blended: {blended.size/10}")
mtk = df[df['Mata Kuliah']=='MTK']
print(f"Jumlah mahasiswa yang belajar matematika: {mtk.size/10}")
absen = df[df['Absen']=='Hadir']
print(f"Jumlah absen yang hadir dikelas: {absen.size/10}")
print(f"Rata-rata IPK: {df.IPK.mean()}")
bea = df[df['Kategori']=='Beasiswa']
non = df[df['Kategori']=='Non Beasiswa']
print(f"Jumlah mahasiswa beasiswa: {bea.size/10}")
print(f"Jumlah mahasiswa non-beasiswa: {non.size/10}")

df.to_csv('dataMahasiswa.CSV')

<bound method DataFrame.info of      Usia Gender Jurusan Asal Sekolah  Semester     Kelas Mata Kuliah  Absen  \
0      18      P      TM           MA         1  Karyawan       Kimia  Sakit
1      19      L      TI          SMK         3  Karyawan         MTK   Izin
2      20      P      TI          SMK         2   Blended       Kimia  Hadir
3      19      P      TS          SMA         3   Reguler       Kimia  Sakit
4      20      L      TM          SMK         3  Karyawan         MTK   Izin
..    ...    ...     ...          ...       ...       ...         ...    ...
995    20      L      TM          SMA         7   Blended       Kimia   Izin
996    19      L      TM          SMK         4  Karyawan       Kimia   Izin
997    22      P      TE          SMA         6   Reguler         MTK   Alfa
998    20      P      TS          SMA         8   Reguler         MTK  Sakit
999    22      P      TS          SMK         1   Reguler      Fisika  Hadir

     IPK      Kategori
0      2      Beasiswa
1      4      Beasiswa
2      4      Beasiswa
3      3      Beasiswa
4      3      Beasiswa
..   ...           ...
995    2      Beasiswa
996    3  Non Beasiswa
997    2      Beasiswa
998    3      Beasiswa
999    2      Beasiswa

[1000 rows x 10 columns]>
Usia mahasiswa termuda: 18
Usia mahasiswa tertua: 22
Jumlah mahasiswa laki-laki: 486.0
Jumlah mahasiswa perempuan: 514.0
Jumlah mahasiswa jurusan Teknik Informatika: 250.0
Jumlah mahasiswa jurusan Teknik Sipil      : 256.0
Jumlah mahasiswa jurusan Teknik Elektro    : 231.0
Jumlah mahasiswa jurusan Teknik Mesin      : 263.0
Jumlah asal sekolah SMA: 338.0
Jumlah asal sekolah SMk: 340.0
Jumlah asal sekolah MA : 322.0
Jumlah mahasiswa semester tua: 2570
Jumlah mahasiswa kelas reguler: 336.0
Jumlah mahasiswa kelas karyawan: 331.0
Jumlah mahasiswa kelas blended: 333.0
Jumlah mahasiswa yang belajar matematika: 315.0
Jumlah absen yang hadir dikelas: 250.0
Rata-rata IPK: 2.996
Jumlah mahasiswa beasiswa: 507.0
Jumlah mahasiswa non-beasiswa: 493.0